name: images

on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Install k3d
      run: |
        curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
    -
      name: Run k3d test
      run: ./test-k3d.sh

  docker:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push k3s-buildkit
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: |
          ghcr.io/turbokube/k3s-buildkit:latest
          ghcr.io/turbokube/k3s-buildkit:${{ github.sha }}
        platforms: linux/amd64,linux/arm64/v8
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
